version: '3.8'
services:
  apigateway:
    build: ./apigateway
    container_name: mt_apigateway_container
    restart: unless-stopped
    env_file:
      - ./apigateway/.env
    ports:
      - "3000:3000"
    environment:
      NATS_SERVER: 'nats://nats:4222'
    entrypoint: ./entrypoint.sh
    depends_on:
      - nats
    volumes:
      - ./apigateway:/usr/src/app
      - /usr/src/app/node_modules

  user:
    build: ./user
    container_name: mt_user_container
    restart: unless-stopped
    env_file:
      - ./user/.env
    environment:
      NATS_SERVER: 'nats://nats:4222'
    entrypoint: ./entrypoint.sh
    volumes:
      - ./user:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      - nats

  tweet:
    build: ./tweet
    container_name: mt_tweet_container
    restart: unless-stopped
    env_file:
      - ./tweet/.env
    environment:
      NATS_SERVER: 'nats://nats:4222'
    entrypoint: ./entrypoint.sh
    volumes:
      - ./tweet:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      - nats

  social:
    build: ./social
    container_name: mt_social_container
    restart: unless-stopped
    env_file:
      - ./social/.env
    environment:
      NATS_SERVER: 'nats://nats:4222'
    entrypoint: ./entrypoint.sh
    volumes:
      - ./social:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - nats

  db:
    image: postgres:13-alpine
    container_name: mt_postgres_container
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    ports:
      - '5432:5432' # for RDMS management tools
    volumes:
      - db:/data/postgres

  nats:
    image: nats:alpine3.16
    container_name: mt_nats_container

volumes:
  db:
    driver: local